try 
{
    throw new ArgumentOutOfRangeException();
}

catch (ArgumentOutOfRangeException) 
{
    Console.WriteLine("Произошла ошибка!!");
}

finally 
{
    
}